### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by fscottfoti** [fscottfoti/houseguesser#2]
- [x] clean up UI in terms of the way listings and guesses look
- [x] count number of bids
- [x] change "bids" to "guesses" in the ui
- [ ] favicon
- [ ] make sure user can only make one bid
- [ ] search listings by zip, city, link, address, and maybe bid/nobid
- [ ] filter bids by user
- [ ] mark listings as sold
- [ ] leaderboards by zip and by city
- [ ] leaderboard by group of users rather than by zip and city

**Comment by fscottfoti** [comment]
Moving to wiki
